apiVersion: v1
kind: Service
metadata:
  name: bookapp-service
spec:
  type: NodePort
  selector:
    app: bookapp
  ports:
    - port: 9898
      protocol: TCP
      targetPort: 8080
      nodePort: 32323
